# Site settings
author: Amanda Contreras
title: Why did you decide to study Software Engineering?â€
header-img: img/home-bg.png
email: amandaben21@aol.com
copyright_name: Amanda Contreras
description: > # this means to ignore newlines until "baseurl:"
  Leading to become a Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  amandaben21

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
